---
title: '&#39;Catch&#39; bloğuna hiç ulaşılmadı, çünkü &#39; &lt;name1&gt; &#39; devraldığı &#39; &lt;name2&gt;&#39;'
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 35ca615dd8fc7bbc0b2d1ae0039e9f2e70e05df6
ms.sourcegitcommit: 2eceb05f1a5bb261291a1f6a91c5153727ac1c19
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 09/04/2018
ms.locfileid: "43510558"
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39;Catch&#39; bloğuna hiç ulaşılmadı, çünkü &#39; &lt;name1&gt; &#39; devraldığı &#39; &lt;name2&gt;&#39;
A `Catch` blok kod içinde hiç ulaşılamadı.  
  
 Varsayılan olarak, bu iletiyi bir uyarıdır. Uyarıları gizleme veya uyarıları hata olarak değerlendirmesini daha fazla bilgi için bkz: [Visual Basic'teki uyarıları yapılandırma](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Hata Kimliği:** BC42029  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
-   Fazla `Catch` blok.  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [Nasıl yapılır: Test kodu ile bir Try... Visual Basic'te catch bloğu](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
