---
title: "Özel Durumlar Kullanma (C# Programlama Kılavuzu)"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-csharp
ms.topic: article
helpviewer_keywords:
- exception handling [C#], about exception handling
- exceptions [C#], about exceptions
ms.assetid: 71472c62-320a-470a-97d2-67995180389d
caps.latest.revision: "15"
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 55c2cc0c6a1f852bd286b98927cc69f81119aeee
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 11/21/2017
---
# <a name="using-exceptions-c-programming-guide"></a><span data-ttu-id="c0b0e-102">Özel Durumlar Kullanma (C# Programlama Kılavuzu)</span><span class="sxs-lookup"><span data-stu-id="c0b0e-102">Using Exceptions (C# Programming Guide)</span></span>
<span data-ttu-id="c0b0e-103">C# ' ta çalışma zamanında programında hataları program aracılığıyla özel durumlar olarak adlandırılan bir mekanizma kullanılarak dağıtılır.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-103">In C#, errors in the program at run time are propagated through the program by using a mechanism called exceptions.</span></span> <span data-ttu-id="c0b0e-104">Özel durumlar hatayla karşılaştığında kodla oluşturulur ve hatayı düzeltmek için kullanabileceğiniz kodla yakalandı.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-104">Exceptions are thrown by code that encounters an error and caught by code that can correct the error.</span></span> <span data-ttu-id="c0b0e-105">.NET Framework ortak dil çalışma zamanı (CLR) veya kod içinde bir program tarafından özel durum.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-105">Exceptions can be thrown by the .NET Framework common language runtime (CLR) or by code in a program.</span></span> <span data-ttu-id="c0b0e-106">Bir özel durum oluşturulduktan sonra çağrı yığını kadar yukarı yayar bir `catch` özel durum bildirimi bulundu.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-106">Once an exception is thrown, it propagates up the call stack until a `catch` statement for the exception is found.</span></span> <span data-ttu-id="c0b0e-107">Yakalanmayan Özel durumlar iletişim kutusu görüntüler sistem tarafından sağlanan bir genel özel durum işleyicisi tarafından işlenir.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-107">Uncaught exceptions are handled by a generic exception handler provided by the system that displays a dialog box.</span></span>  
  
 <span data-ttu-id="c0b0e-108">Özel durumlar türetilmiş sınıflar tarafından gösterilen <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-108">Exceptions are represented by classes derived from <xref:System.Exception>.</span></span> <span data-ttu-id="c0b0e-109">Bu sınıf, özel durum türünü tanımlar ve özel durum ayrıntıları sahip özellikler içerir.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-109">This class identifies the type of exception and contains properties that have details about the exception.</span></span> <span data-ttu-id="c0b0e-110">Bir özel durum atma içerir bir özel durum türetilmiş sınıf örneği oluşturmayı, isteğe bağlı olarak özel özelliklerini yapılandırmak ve ardından kullanarak nesne atma `throw` anahtar sözcüğü.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-110">Throwing an exception involves creating an instance of an exception-derived class, optionally configuring properties of the exception, and then throwing the object by using the `throw` keyword.</span></span> <span data-ttu-id="c0b0e-111">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="c0b0e-111">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#1](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_1.cs)]  
  
 <span data-ttu-id="c0b0e-112">Bir özel durum oluşturulduktan sonra çalışma zamanı geçerli deyimi içinde olup olmadığını denetler. bir `try` bloğu.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-112">After an exception is thrown, the runtime checks the current statement to see whether it is within a `try` block.</span></span> <span data-ttu-id="c0b0e-113">Bunu varsa, `catch` ilişkili blokları `try` bloğu, bunlar özel durum catch olup olmadığını görmek için denetlenir.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-113">If it is, any `catch` blocks associated with the `try` block are checked to see whether they can catch the exception.</span></span> <span data-ttu-id="c0b0e-114">`Catch`blokları genellikle özel durum türleri belirtin; varsa türünü `catch` bloğu özel durum ya da bir taban sınıf özel durum, aynı türde `catch` blok yöntemi işleyebilir.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-114">`Catch` blocks typically specify exception types; if the type of the `catch` block is the same type as the exception, or a base class of the exception, the `catch` block can handle the method.</span></span> <span data-ttu-id="c0b0e-115">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="c0b0e-115">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#2](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_2.cs)]  
  
 <span data-ttu-id="c0b0e-116">Aykırı deyimi içinde değilse, bir `try` blok veya `try` onu blok eşleşen sahip `catch` bloğu, çalışma zamanı için arama yöntemi olup olmadığına bakar bir `try` deyimi ve `catch` engeller.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-116">If the statement that throws an exception is not within a `try` block or if the `try` block that encloses it has no matching `catch` block, the runtime checks the calling method for a `try` statement and `catch` blocks.</span></span> <span data-ttu-id="c0b0e-117">Çalışma zamanı için uyumlu bir arama Çağırma yığını yukarı devam `catch` bloğu.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-117">The runtime continues up the calling stack, searching for a compatible `catch` block.</span></span> <span data-ttu-id="c0b0e-118">Sonra `catch` bloğu bulundu ve yürütülen, Denetim bundan sonra next deyimi iletilir `catch` bloğu.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-118">After the `catch` block is found and executed, control is passed to the next statement after that `catch` block.</span></span>  
  
 <span data-ttu-id="c0b0e-119">A `try` deyimi birden fazla içerebilir `catch` bloğu.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-119">A `try` statement can contain more than one `catch` block.</span></span> <span data-ttu-id="c0b0e-120">İlk `catch` özel durumu işleyebilecek deyimi yürütüldüğünde; tüm aşağıdaki `catch` deyimleri uyumlu olsalar bile, yok sayılır.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-120">The first `catch` statement that can handle the exception is executed; any following `catch` statements, even if they are compatible, are ignored.</span></span> <span data-ttu-id="c0b0e-121">Bu nedenle, catch blokları her zaman sıralı en belirli (veya en çok türetilen) az.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-121">Therefore, catch blocks should always be ordered from most specific (or most-derived) to least specific.</span></span> <span data-ttu-id="c0b0e-122">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="c0b0e-122">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#3](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs)]  
  
 <span data-ttu-id="c0b0e-123">Önce `catch` blok yürütüldüğünde, çalışma zamanı denetler `finally` engeller.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-123">Before the `catch` block is executed, the runtime checks for `finally` blocks.</span></span> <span data-ttu-id="c0b0e-124">`Finally`blokları etkinleştirmek durdurulan kalabilir herhangi bir belirsiz durumu temizlemek Programcı `try` bloğu veya herhangi bir dış kaynağa (örneğin, grafik tanıtıcıları, veritabanı bağlantılarını veya dosya akışları) için çöp beklemeden serbest bırakmak için nesneleri sonlandırmaya Toplayıcı çalışma zamanında.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-124">`Finally` blocks enable the programmer to clean up any ambiguous state that could be left over from an aborted `try` block, or to release any external resources (such as graphics handles, database connections or file streams) without waiting for the garbage collector in the runtime to finalize the objects.</span></span> <span data-ttu-id="c0b0e-125">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="c0b0e-125">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#4](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_4.cs)]  
  
 <span data-ttu-id="c0b0e-126">Varsa `WriteByte()` ikinci kodda özel durum oluşturdu `try` , dosyayı yeniden dener blok başarısız olurdu `file.Close()` adlı değil ve dosyanın kilitli olarak kalır.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-126">If `WriteByte()` threw an exception, the code in the second `try` block that tries to reopen the file would fail if `file.Close()` is not called, and the file would remain locked.</span></span> <span data-ttu-id="c0b0e-127">Olduğundan `finally` blokları bir özel durum olsa bile, yürütülen `finally` önceki örnekte blok dosyanın doğru kapatılması sağlar ve yardımcı bir hata kaçının.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-127">Because `finally` blocks are executed even if an exception is thrown, the `finally` block in the previous example allows for the file to be closed correctly and helps avoid an error.</span></span>  
  
 <span data-ttu-id="c0b0e-128">Hiçbir uyumlu değilse `catch` blok bulundu çağrı yığınındaki bir özel durum oluşturulduktan sonra üç şey biri oluşur:</span><span class="sxs-lookup"><span data-stu-id="c0b0e-128">If no compatible `catch` block is found on the call stack after an exception is thrown, one of three things occurs:</span></span>  
  
-   <span data-ttu-id="c0b0e-129">Özel durum sonlandırıcıyı içinde ise, sonlandırıcıyı iptal edilir ve temel sonlandırıcıyı varsa çağrılır.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-129">If the exception is within a finalizer, the finalizer is aborted and the base finalizer, if any, is called.</span></span>  
  
-   <span data-ttu-id="c0b0e-130">Çağrı yığını statik oluşturucu veya bir statik alan Başlatıcı içeriyorsa bir <xref:System.TypeInitializationException> atanan özgün özel durum <xref:System.Exception.InnerException%2A> yeni özel durum özelliği.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-130">If the call stack contains a static constructor, or a static field initializer, a <xref:System.TypeInitializationException> is thrown, with the original exception assigned to the <xref:System.Exception.InnerException%2A> property of the new exception.</span></span>  
  
-   <span data-ttu-id="c0b0e-131">İş parçacığının başlangıcını ulaştıysanız, iş parçacığı sonlandırılır.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-131">If the start of the thread is reached, the thread is terminated.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="c0b0e-132">Ayrıca Bkz.</span><span class="sxs-lookup"><span data-stu-id="c0b0e-132">See Also</span></span>  
 [<span data-ttu-id="c0b0e-133">C# programlama kılavuzu</span><span class="sxs-lookup"><span data-stu-id="c0b0e-133">C# Programming Guide</span></span>](../../../csharp/programming-guide/index.md)  
 [<span data-ttu-id="c0b0e-134">Özel durumlar ve özel durum işleme</span><span class="sxs-lookup"><span data-stu-id="c0b0e-134">Exceptions and Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/index.md)
